linters:
  enable-all: true
  disable:
    - depguard
    - execinquery #  The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.  
    - exhaustruct
    - exportloopref # The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
    - gochecknoglobals
    - nlreturn
    - nolintlint
    - tenv # The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature another linter. Replaced by usetesting.
    - testableexamples
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-files:
    - example_test.go
  exclude-rules:
    - path: _test\.go
      linters:
        - err113
        - forcetypeassert
        - funlen
linters-settings:
  cyclop:
    skip-tests: true
  lll:
    line-length: 200
